sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jiyoon/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true jiyoon/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react-appn
  env: Dockerreactappn-env
  bucket_name: elasticbeanstalk-us-east-1-787808573525
  bucket_path: docker-react-appn
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
 